### ISSUE TITLE
Hi bruv is it possible to do this addon on 4.3.4 versions?

### ISSUE THREAD

**Issue by corp6x** [z0fa/WoWQuestTTS#10]
Very soon will be released Cataclysm Classic and this addon will kick off for sure too, is it possible to make it 4.3.4 retail too allready rn, the patch probably did not has many changes and probably you allready has woltk version so it very perfect!

**Comment by corp6x** [comment]
@z0fa

**Comment by z0fa** [comment]
The interface code should be pretty much the same so it should work with minimal edits. As soon Cataclysm Classic will be released I'll update the addon 👍

**Comment by z0fa** [comment]
Experimental support added in 1.30
