### ISSUE TITLE
Azure or other tts voice API

### ISSUE THREAD

**Issue by jbomhold3** [z0fa/WoWQuestTTS#13]
Can we get optional settings for Azure TTS added? Of course, everyone would need to use their own API key.

**Comment by z0fa** [comment]
Addons cannot comunicate with services outside the game, but you can try  [JocysCom TTS](https://github.com/JocysCom/TextToSpeech) which can use Amazon cloud tts

**Comment by BelegCufea** [comment]
You can also check [SAPI Adapter]( https://github.com/gexgd0419/NaturalVoiceSAPIAdapter)
