### ISSUE TITLE
New errors after the 11.0.2 update

### ISSUE THREAD

**Issue by JyanseiCoding** [z0fa/WoWQuestTTS#17]
> 1x Blizzard_Settings_Shared/Blizzard_Setting.lua:383: 'variableTbl' argument must be a table.
> [string "=[C]"]: in function `assert'
> [string "@Blizzard_Settings_Shared/Blizzard_Setting.lua"]:383: in function `Init'
> [string "@Blizzard_SharedXMLBase/Mixin.lua"]:28: in function <Blizzard_SharedXMLBase/Mixin.lua:26>
> [string "@Blizzard_Settings_Shared/Blizzard_SettingsInbound.lua"]:197: in function <...lizzard_Settings_Shared/Blizzard_SettingsInbound.lua:155>
> [string "=[C]"]: in function `SetAttribute'
> [string "@Blizzard_Settings_Shared/Blizzard_SettingsInbound.lua"]:98: in function <...lizzard_Settings_Shared/Blizzard_SettingsInbound.lua:97>
> [string "=(tail call)"]: ?
> [string "@QuestTTS/src/expansions/retail.lua"]:56: in function `proxySetting'
> [string "@QuestTTS/src/expansions/retail.lua"]:81: in function `initSettings'
> [string "@QuestTTS/src/main.lua"]:39: in function `fn'
> [string "@QuestTTS/libs/addon.lua"]:382: in function `callbackFn'
> [string "@QuestTTS/libs/array.lua"]:164: in function `forEach'
> [string "@QuestTTS/libs/addon.lua"]:380: in function <QuestTTS/libs/addon.lua:378>
> [string "@QuestTTS/libs/addon.lua"]:166: in function `handler'
> [string "@QuestTTS/libs/addon.lua"]:371: in function `callbackFn'
> [string "@QuestTTS/libs/array.lua"]:164: in function `forEach'
> [string "@QuestTTS/libs/addon.lua"]:369: in function <QuestTTS/libs/addon.lua:365>
> 
> Locals:
> (*temporary) = false
> (*temporary) = "'variableTbl' argument must be a table."

> 1x ...ddOns/Blizzard_Settings_Shared/Blizzard_Settings.lua:351: attempt to call method 'GetVariableType' (a nil value)
> [string "@Blizzard_Settings_Shared/Blizzard_Settings.lua"]:351: in function `CreateCheckboxInitializer'
> [string "@Blizzard_Settings_Shared/Blizzard_Settings.lua"]:375: in function <...ddOns/Blizzard_Settings_Shared/Blizzard_Settings.lua:374>
> [string "=(tail call)"]: ?
> [string "@QuestTTS/src/expansions/retail.lua"]:84: in function `initSettings'
> [string "@QuestTTS/src/main.lua"]:39: in function `fn'
> [string "@QuestTTS/libs/addon.lua"]:382: in function `callbackFn'
> [string "@QuestTTS/libs/array.lua"]:164: in function `forEach'
> [string "@QuestTTS/libs/addon.lua"]:380: in function <QuestTTS/libs/addon.lua:378>
> [string "@QuestTTS/libs/addon.lua"]:166: in function `handler'
> [string "@QuestTTS/libs/addon.lua"]:371: in function `callbackFn'
> [string "@QuestTTS/libs/array.lua"]:164: in function `forEach'
> [string "@QuestTTS/libs/addon.lua"]:369: in function <QuestTTS/libs/addon.lua:365>
> 
> Locals:
> setting = <table> {
>  order = 41
>  ID = 41
>  name = "QuestTTS"
>  subcategories = <table> {
>  }
> }
> options = nil
> tooltip = ""
> (*temporary) = nil
> (*temporary) = <table> {
>  order = 41
>  ID = 41
>  name = "QuestTTS"
>  subcategories = <table> {
>  }
> }
> (*temporary) = "attempt to call method 'GetVariableType' (a nil value)"

**Comment by BelegCufea** [comment]
Just made PR, that should work until [z0fa](https://github.com/z0fa) creates proper fix.
