### ISSUE TITLE
Unable to select TTS voice from list.

### ISSUE THREAD

**Issue by MrMartiniMo** [z0fa/WoWQuestTTS#2]
Hi, I was unable to select the correct voice from the list because it is not scrollable.

QuestTTS-1.17
MacBook Air M2, 2022
WoW 10.0.0.46549
Resolution 2560x1664

<img width="1710" alt="image" src="https://user-images.githubusercontent.com/1511660/200928654-eda56eb9-4a97-4696-a5b8-85871b4d6aeb.png">

Anyway nice addon 👍

**Comment by MrMartiniMo** [comment]
My quick fix is to hardcode the voices in `main.lua`

```lua
function module.getVoice()
  local toRet = settings.voice1.get()
  local unitSex = UnitSex("questnpc") or UnitSex("npc")

  if unitSex == 2 then -- male
    toRet = 55 --settings.voice1.get()
  elseif unitSex == 3 then -- female
    toRet = 48 --settings.voice2.get()
  else
    toRet = 64 --settings.voice3.get()
  end

  local voices = Array.new(C_VoiceChat.GetTtsVoices())
  local voiceToRet = voices:find(
    function(v)
      if v.voiceID == toRet then
        return true
      end
    end
  )

  return voiceToRet
end
```

I used this code to output all German voices and it's voiceIDs:
```lua
print('-------------------------')

table.foreach(
   C_VoiceChat.GetTtsVoices(),
   function(k,v)
      if string.find(v.name, 'DE') then
         print(v.voiceID .. ': ' .. v.name)
      end
   end
)

print('-------------------------')
```

**Comment by z0fa** [comment]
Oh wow, where did you get all this voices from? I'm migrating the addon settings to the new api, the new slectbox should be scrollable by default. There are some taint errors with the new api, i'm wating for a fix before releasing the new version...

Thank you for the report :)

**Comment by MrMartiniMo** [comment]
I think it is default on macOS but I am not sure 😅 Thank you for your quick reply. Really nice Addon, I love it 👍

**Comment by z0fa** [comment]
Can you try to update to the latest version and check if you are still having the issue?
Thanks

**Comment by MrMartiniMo** [comment]
Hi @z0fa 

now it looks like this. It's ok. I can access all the voices and I like the up and down buttons 👍
Maybe you can add a preview button to test the voice for a future release.

<img width="784" alt="image" src="https://user-images.githubusercontent.com/1511660/203383088-94f686e1-5a80-4ace-b3cd-aa1bf4a00d3c.png">

**Comment by z0fa** [comment]
Yeah, I'll definitely add a preview button in a future update
Thank you :)
