### ISSUE TITLE
Can't select TTS voice

### ISSUE THREAD

**Issue by Astraorion** [z0fa/WoWQuestTTS#21]
Hi, I can't select any voice, no QuestTTS setting is appearing in add-ons

What can I do?

System: 
Mac Mini M1

WoW: 4.4.1.57294

<img width="312" alt="Bild" src="https://github.com/user-attachments/assets/a8c57c01-2e92-43c7-a2df-1e7fa813fb50">

**Comment by z0fa** [comment]
Should be fixed in the latest release (1.36)
