### ISSUE TITLE
Addon no longer works with Immersion and wont auto read if npc has more than one quest.

### ISSUE THREAD

**Issue by Booggg** [z0fa/WoWQuestTTS#4]
Disabled all addons. 
Using only tts and immersion, if the npc has more than one quest tts wont read anything, if npc has 1 quest it will auto read.

with tts only if npc has one quest it will auto read. if more than one quest have to manually click play button.

https://www.youtube.com/watch?v=j1d0Jm6hyGo
Uploaded vid to better display what I mean

**Comment by z0fa** [comment]
Thank you for the report, the issue should be fixed in the latest version, please update the addon and let me know :)

**Comment by Booggg** [comment]
Seems to work. Thanks.

**Comment by z0fa** [comment]
yeah the tts is being triggered by the Immersion dialog and by the native (hidden) gossip dialog, I'll publish a new release tomorrow with a few other fixes 👍
