### ISSUE TITLE
Lua Error in 10.1.7

### ISSUE THREAD

**Issue by JyanseiCoding** [z0fa/WoWQuestTTS#8]
Action blocked function available only to Blizzard

1x [ADDON_ACTION_FORBIDDEN] AddOn 'QuestTTS' tried to call the protected function 'SpellStopCasting()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `SpellStopCasting'
[string "@FrameXML/UIParent.lua"]:4113: in function `ToggleGameMenu'
[string "@SharedXML/Settings/Blizzard_SettingsPanel.lua"]:359: in function `TransitionBackOpeningPanel'
[string "@SharedXML/Settings/Blizzard_SettingsPanel.lua"]:348: in function `ExitWithCommit'
[string "@SharedXML/Settings/Blizzard_SettingsPanel.lua"]:317: in function `Close'
[string "@SharedXML/Settings/Blizzard_SettingsPanel.lua"]:76: in function <SharedXML/Settings/Blizzard_SettingsPanel.lua:75>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507
}

All I did was literally just open the settings and close and this popped up. I'm guessing this is taint issue from Blizzard's side?

**Comment by z0fa** [comment]
Hello @JyanseiCoding, thank you for your feedback 😀
Can you please check if by disabling all the other addons do you still have the issue? I have done some testing but couldn't reproduce the issue 😕

**Comment by JyanseiCoding** [comment]
I'm unable to replicate this error, with or without all other addons disabled. I'm guessing it was a fluke.

I'll close this for now and update you in case I come across it again in the future.
